apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: api-deployment-demo
  labels:
    app: postgres
    component: database
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9187
      targetPort: 9187
  type: ClusterIP

---
# Separate service for Prometheus metrics scraping
apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics
  namespace: api-deployment-demo
  labels:
    app: api-demo
    component: database
spec:
  selector:
    app: postgres
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
  type: ClusterIP
